development:
  access_key_id: AKIAJ6QTTSLR7EITXZMA
  secret_access_key: 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

production:
  access_key_id: AKIAJ6QTTSLR7EITXZMA
  secret_access_key: 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